substitutions:
  name: esp32-wroom2
  version: "24.10.25.0"
  device_description: ${name} made by Larry Greenwald - version ${version}.
  friendly_name: ESP32 Wroom2

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: ESP32 Wroom2
  name_add_mac_suffix: False
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "LarryGreenwald.${name}"
    version: "${version}"

  min_version: 2024.6.0

esp32:
  board: esp32dev
  framework:
    type: esp-idf

dashboard_import:
  package_import_url: github://ApolloAutomation/AIR-1/Integrations/ESPHome/AIR-1.yaml
  import_full_config: false

# Enable logging
logger:
  level: NONE
# Enable Home Assistant API
api:
  encryption:
    key: !secret esp32-devkit1-api-key

ota:
  - platform: esphome
    password: !secret ota-password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: LIGHT

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: !secret ap_password

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.193   # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
    dns1: 192.168.1.181
    dns2: 192.168.1.107

captive_portal:

safe_mode:

web_server:
  port: 80

sensor:
  - platform: internal_temperature
    name: "ESP Temperature"
    id: sys_esp_temperature

  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: " IP"
      icon: "mdi:ip-outline"
